-- Run this ONCE in Supabase (SQL Editor) to make the gallery fully manageable.
-- 1) Adds the column the gallery uses to store a direct image URL (for your existing photos).
-- 2) Imports your 65 existing gallery photos as manageable records.
-- Safe + additive: it does not touch any other table.

alter table public.gallery_photos add column if not exists image_url text;

insert into public.gallery_photos (image_url, category, sort_order) values
  ('/images/gallery/updo-01.jpg', 'updo', 1),
  ('/images/gallery/waves-01.jpg', 'waves', 2),
  ('/images/gallery/party-01.jpg', 'party', 3),
  ('/images/gallery/updo-02.jpg', 'updo', 4),
  ('/images/gallery/waves-02.jpg', 'waves', 5),
  ('/images/gallery/makeup-01.jpg', 'makeup', 6),
  ('/images/gallery/updo-03.jpg', 'updo', 7),
  ('/images/gallery/waves-03.jpg', 'waves', 8),
  ('/images/gallery/party-02.jpg', 'party', 9),
  ('/images/gallery/updo-04.jpg', 'updo', 10),
  ('/images/gallery/waves-04.jpg', 'waves', 11),
  ('/images/gallery/makeup-02.jpg', 'makeup', 12),
  ('/images/gallery/updo-05.jpg', 'updo', 13),
  ('/images/gallery/waves-05.jpg', 'waves', 14),
  ('/images/gallery/party-03.jpg', 'party', 15),
  ('/images/gallery/updo-06.jpg', 'updo', 16),
  ('/images/gallery/waves-06.jpg', 'waves', 17),
  ('/images/gallery/makeup-03.jpg', 'makeup', 18),
  ('/images/gallery/updo-07.jpg', 'updo', 19),
  ('/images/gallery/waves-07.jpg', 'waves', 20),
  ('/images/gallery/party-04.jpg', 'party', 21),
  ('/images/gallery/updo-08.jpg', 'updo', 22),
  ('/images/gallery/waves-08.jpg', 'waves', 23),
  ('/images/gallery/updo-09.jpg', 'updo', 24),
  ('/images/gallery/waves-09.jpg', 'waves', 25),
  ('/images/gallery/party-05.jpg', 'party', 26),
  ('/images/gallery/updo-10.jpg', 'updo', 27),
  ('/images/gallery/waves-10.jpg', 'waves', 28),
  ('/images/gallery/updo-11.jpg', 'updo', 29),
  ('/images/gallery/waves-11.jpg', 'waves', 30),
  ('/images/gallery/party-06.jpg', 'party', 31),
  ('/images/gallery/updo-12.jpg', 'updo', 32),
  ('/images/gallery/waves-12.jpg', 'waves', 33),
  ('/images/gallery/updo-13.jpg', 'updo', 34),
  ('/images/gallery/waves-13.jpg', 'waves', 35),
  ('/images/gallery/party-07.jpg', 'party', 36),
  ('/images/gallery/updo-14.jpg', 'updo', 37),
  ('/images/gallery/waves-14.jpg', 'waves', 38),
  ('/images/gallery/updo-15.jpg', 'updo', 39),
  ('/images/gallery/waves-15.jpg', 'waves', 40),
  ('/images/gallery/party-08.jpg', 'party', 41),
  ('/images/gallery/updo-16.jpg', 'updo', 42),
  ('/images/gallery/waves-16.jpg', 'waves', 43),
  ('/images/gallery/updo-17.jpg', 'updo', 44),
  ('/images/gallery/waves-17.jpg', 'waves', 45),
  ('/images/gallery/party-09.jpg', 'party', 46),
  ('/images/gallery/updo-18.jpg', 'updo', 47),
  ('/images/gallery/waves-18.jpg', 'waves', 48),
  ('/images/gallery/updo-19.jpg', 'updo', 49),
  ('/images/gallery/waves-19.jpg', 'waves', 50),
  ('/images/gallery/party-10.jpg', 'party', 51),
  ('/images/gallery/updo-20.jpg', 'updo', 52),
  ('/images/gallery/waves-20.jpg', 'waves', 53),
  ('/images/gallery/updo-21.jpg', 'updo', 54),
  ('/images/gallery/waves-21.jpg', 'waves', 55),
  ('/images/gallery/party-11.jpg', 'party', 56),
  ('/images/gallery/updo-22.jpg', 'updo', 57),
  ('/images/gallery/waves-22.jpg', 'waves', 58),
  ('/images/gallery/updo-23.jpg', 'updo', 59),
  ('/images/gallery/waves-23.jpg', 'waves', 60),
  ('/images/gallery/party-12.jpg', 'party', 61),
  ('/images/gallery/updo-24.jpg', 'updo', 62),
  ('/images/gallery/updo-25.jpg', 'updo', 63),
  ('/images/gallery/party-13.jpg', 'party', 64),
  ('/images/gallery/updo-26.jpg', 'updo', 65);
